/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lee_feathercnnexdemo_JniActivity */

#ifndef _Included_com_example_lee_feathercnnexdemo_JniActivity
#define _Included_com_example_lee_feathercnnexdemo_JniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lee_feathercnnexdemo_JniActivity
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_lee_feathercnnexdemo_JniActivity_getEdge
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_lee_feathercnnexdemo_JniActivity
 * Method:    FeatherCNNExTest
 * Signature: (Lcom/example/lee/feathercnnexdemo/RuntimeArgs;)I
 */
JNIEXPORT jint JNICALL Java_com_example_lee_feathercnnexdemo_JniActivity_FeatherCNNExTest
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
